---
sudo: required
dist: trusty
group: deprecated-2017Q2

language: python
python: "2.7"

env:
  - INVENTORY=tests/inventory; TEST_PLAY=tests/test.yml

before_install:
  - sudo apt-get update -qq
  # Clean up all the weird rubies (none coming from apt packages) from system
  - sudo rm /usr/bin/ruby /usr/bin/gem

install:
  # Setup ruby 2.0 for root
  - sudo apt-get install -y ruby2.0
  - sudo ln -s /usr/bin/ruby2.0 /usr/bin/ruby
  - sudo ln -s /usr/bin/gem2.0 /usr/bin/gem
  - sudo ln -s /usr/bin/rake2.0 /usr/bin/rake

  # Install serverspec as root
  - sudo ruby -v
  - sudo gem install serverspec

  # Install Ansible
  - pip install ansible
  - ansible --version

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i $INVENTORY --syntax-check $TEST_PLAY

  # Run the role/playbook with ansible-playbook.
  - ansible-playbook -i $INVENTORY --connection=local $TEST_PLAY

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i $INVENTORY --connection=local $TEST_PLAY
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Run nginx config test
  - sudo nginx -t

  # Run serverspec
  - sudo rake spec
