---
sudo: required
dist: xenial

language: python
python: "2.7"

env:
  - INVENTORY=tests/inventory; TEST_PLAY=tests/test.yml

install:
  # Setup ruby to run serverspec tests
  - ruby -v
  - gem install serverspec

  # Install Ansible
  - pip install ansible
  - ansible --version

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i $INVENTORY --syntax-check $TEST_PLAY

  # Run the role/playbook with ansible-playbook.
  - ansible-playbook -i $INVENTORY --connection=local $TEST_PLAY

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i $INVENTORY --connection=local $TEST_PLAY
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Run nginx config test
  - sudo nginx -t

  # Run serverspec
  - rake spec
